### ISSUE TITLE
Cannot read property 'toISOString' of undefined

### ISSUE THREAD

**Issue by martinstoyanov** [Ephigenia/ikea-availability-checker#12] opened 2020-07-29 10:25 UTC
This issue arises sometimes, not every time but once it is there it keeps on happening.

Query: ```npm run start -- stock --country us S19282863```

Output: 

```
(node:17224) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toISOString' of undefined
    at /Users/martinstoyanov/Downloads/ikea/node_modules/ikea-availability-checker/source/lib/reporter/stock-table.js:57:32
    at Array.map (<anonymous>)
    at Object.createReport (/Users/martinstoyanov/Downloads/ikea/node_modules/ikea-availability-checker/source/lib/reporter/stock-table.js:56:8)
    at /Users/martinstoyanov/Downloads/ikea/node_modules/ikea-availability-checker/source/cli-stock.js:114:45
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:17224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm on the latest version. Thanks!

**Comment by eslendil** [comment] 2020-07-31 18:07
how do you run this ?

**Comment by Ephigenia** [comment] 2020-07-31 21:20
I‘ll check this later. Probably an empty or invalid response. Needs debugging in the response handling.

**Comment by Ephigenia** [comment] 2020-08-10 16:45
Thanks for finding this.

Unfortunatly I’m not able to reproduce the issue by running the command this time:
```
npm run start -- stock --country us S19282863
```

However, I think that the issue might be caused by an response that contains unexpected data and/or nested objects which result to an `availability` which is `undefined`.

Can you please run the command again using the DEBUG environment variable to get some more debug information about the reply from the IOWS API:

```
DEBUG=* npm run start -- stock --country us S19282863
```

That information might help me to fix this issue.

**Comment by Ephigenia** [comment] 2020-08-19 20:11
@martinstoyanov can you please confirm that the issue is still happening or not. I’ll like to close this issue in some time when the problem is not active at the moment.

**Closed** 2020-08-26 08:18 UTC
Labels: question
